// File: TelegramPanel/Infrastructure/Helper/CountryHelper.cs
namespace TelegramPanel.Infrastructure.Helper
{
    public static class CountryHelper
    {
        /// <summary>
        /// Provides a comprehensive list of countries with their names (including flag emoji) and ISO 3166-1 Alpha-2 codes.
        /// </summary>
        public static readonly List<(string Name, string Code)> AllCountries =
        [
            // --- Priority Countries ---
            ("🇮🇷 Iran", "IR"),
            ("🇺🇸 United States", "US"),
            ("🇩🇪 Germany", "DE"),
            ("🇬🇧 United Kingdom", "GB"),
            ("🇫🇷 France", "FR"),
            ("🇯🇵 Japan", "JP"),
            ("🇨🇦 Canada", "CA"),
            ("🇦🇺 Australia", "AU"),
            ("🇨🇳 China", "CN"),
            ("🇷🇺 Russia", "RU"),
            ("🇮🇳 India", "IN"),
            ("🇧🇷 Brazil", "BR"),

            // --- Expanded List (Alphabetical) ---
            ("🇦🇫 Afghanistan", "AF"),
            ("🇦🇱 Albania", "AL"),
            ("🇩🇿 Algeria", "DZ"),
            ("🇦🇩 Andorra", "AD"),
            ("🇦🇴 Angola", "AO"),
            ("🇦🇷 Argentina", "AR"),
            ("🇦🇲 Armenia", "AM"),
            ("🇦🇹 Austria", "AT"),
            ("🇦🇿 Azerbaijan", "AZ"),
            ("🇧🇭 Bahrain", "BH"),
            ("🇧🇩 Bangladesh", "BD"),
            ("🇧🇾 Belarus", "BY"),
            ("🇧🇪 Belgium", "BE"),
            ("🇧🇴 Bolivia", "BO"),
            ("🇧🇦 Bosnia & Herzegovina", "BA"),
            ("🇧🇼 Botswana", "BW"),
            ("🇧🇬 Bulgaria", "BG"),
            ("🇰🇭 Cambodia", "KH"),
            ("🇨🇲 Cameroon", "CM"),
            ("🇨🇱 Chile", "CL"),
            ("🇨🇴 Colombia", "CO"),
            ("🇨🇷 Costa Rica", "CR"),
            ("🇭🇷 Croatia", "HR"),
            ("🇨🇺 Cuba", "CU"),
            ("🇨🇾 Cyprus", "CY"),
            ("🇨🇿 Czechia", "CZ"),
            ("🇨🇩 Congo (DRC)", "CD"),
            ("🇩🇰 Denmark", "DK"),
            ("🇩🇴 Dominican Republic", "DO"),
            ("🇪🇨 Ecuador", "EC"),
            ("🇪🇬 Egypt", "EG"),
            ("🇸🇻 El Salvador", "SV"),
            ("🇪🇪 Estonia", "EE"),
            ("🇪🇹 Ethiopia", "ET"),
            ("🇫🇮 Finland", "FI"),
            ("🇬🇪 Georgia", "GE"),
            ("🇬🇭 Ghana", "GH"),
            ("🇬🇷 Greece", "GR"),
            ("🇬🇹 Guatemala", "GT"),
            ("🇭🇰 Hong Kong", "HK"),
            ("🇭🇺 Hungary", "HU"),
            ("🇮🇸 Iceland", "IS"),
            ("🇮🇩 Indonesia", "ID"),
            ("🇮🇶 Iraq", "IQ"),
            ("🇮🇪 Ireland", "IE"),
            ("🇮🇱 Israel", "IL"),
            ("🇮🇹 Italy", "IT"),
            ("🇯🇲 Jamaica", "JM"),
            ("🇯🇴 Jordan", "JO"),
            ("🇰🇿 Kazakhstan", "KZ"),
            ("🇰🇪 Kenya", "KE"),
            ("🇰🇼 Kuwait", "KW"),
            ("🇰🇬 Kyrgyzstan", "KG"),
            ("🇱🇻 Latvia", "LV"),
            ("🇱🇧 Lebanon", "LB"),
            ("🇱🇾 Libya", "LY"),
            ("🇱🇹 Lithuania", "LT"),
            ("🇱🇺 Luxembourg", "LU"),
            ("🇲🇾 Malaysia", "MY"),
            ("🇲🇹 Malta", "MT"),
            ("🇲🇽 Mexico", "MX"),
            ("🇲🇩 Moldova", "MD"),
            ("🇲🇳 Mongolia", "MN"),
            ("🇲🇪 Montenegro", "ME"),
            ("🇲🇦 Morocco", "MA"),
            ("🇲🇲 Myanmar", "MM"),
            ("🇳🇵 Nepal", "NP"),
            ("🇳🇱 Netherlands", "NL"),
            ("🇳🇿 New Zealand", "NZ"),
            ("🇳🇬 Nigeria", "NG"),
            ("🇲🇰 North Macedonia", "MK"),
            ("🇳🇴 Norway", "NO"),
            ("🇴🇲 Oman", "OM"),
            ("🇵🇰 Pakistan", "PK"),
            ("🇵🇦 Panama", "PA"),
            ("🇵🇾 Paraguay", "PY"),
            ("🇵🇪 Peru", "PE"),
            ("🇵🇭 Philippines", "PH"),
            ("🇵🇱 Poland", "PL"),
            ("🇵🇹 Portugal", "PT"),
            ("🇶🇦 Qatar", "QA"),
            ("🇷🇴 Romania", "RO"),
            ("🇸🇦 Saudi Arabia", "SA"),
            ("🇷🇸 Serbia", "RS"),
            ("🇸🇬 Singapore", "SG"),
            ("🇸🇰 Slovakia", "SK"),
            ("🇸🇮 Slovenia", "SI"),
            ("🇿🇦 South Africa", "ZA"),
            ("🇰🇷 South Korea", "KR"),
            ("🇪🇸 Spain", "ES"),
            ("🇱🇰 Sri Lanka", "LK"),
            ("🇸🇪 Sweden", "SE"),
            ("🇨🇭 Switzerland", "CH"),
            ("🇸🇾 Syria", "SY"),
            ("🇹🇼 Taiwan", "TW"),
            ("🇹🇿 Tanzania", "TZ"),
            ("🇹🇭 Thailand", "TH"),
            ("🇹🇳 Tunisia", "TN"),
            ("🇹🇷 Turkey", "TR"),
            ("🇺🇬 Uganda", "UG"),
            ("🇺🇦 Ukraine", "UA"),
            ("🇦🇪 United Arab Emirates", "AE"),
            ("🇺🇾 Uruguay", "UY"),
            ("🇻🇪 Venezuela", "VE"),
            ("🇻🇳 Vietnam", "VN"),
            ("🇿🇼 Zimbabwe", "ZW")
        ];
    }
}